### ISSUE TITLE
Algorithm for tracking and choose right area

### ISSUE THREAD

**Issue by slepyce** [teamCarel/EyeTracker#15]

**Comment by ToraCZ** [comment]
Algorithm:

1.  Durign calibration, find and save X and Y screen limits (maximum and minimum values)
2.  Split the range defined by those limits to fit the grid.
3.  Track gaze position and select any tile which the user fixated gaze on for the last 30s for at least 80% of the time. Use confidence threshold to filter out any errors.
4. Light up or otherwise mark the selected tile.

**Comment by ToraCZ** [comment]
Calibration limit finding added in 0f470844394ad4de6c58d277cae0be5546f2892b

**Comment by ToraCZ** [comment]
Whole algorithm finished in 8046f12b98168ae5cdf931396493e9f12e54f6eb
